---
name: Linux-USBKeyboard
version: 0.02
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: access devices pretending to be qwerty keyboards
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Inline::C: 0
  perl: 5.008002
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  Linux::USBKeyboard:
    file: lib/Linux/USBKeyboard.pm
    version: 0.02
  Linux::USBKeyboard::FileHandle:
    file: lib/Linux/USBKeyboard.pm
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
